"""
Código compartilhado entre as duas automações (inscrição e presença):
chamadas à API do Bitrix24, chamadas à API da Sympla, e as funções de
normalização/matching usadas pelas duas pontas.

Este pacote substitui o antigo common.py de arquivo único, dividido por
responsabilidade (bitrix_client / sympla_client / normalization /
constants). Este __init__.py reexporta tudo que já circulava como
"from common import X" antes da divisão — nenhum ponto de import de fora
deste pacote precisa mudar.
"""

from .bitrix_client import (
    _merge_enum_items,
    bitrix_call,
    bitrix_list_all,
    ensure_enum_value,
    find_contact_ids_by_email,
    find_contact_ids_by_phone,
    find_lead_ids_by_email,
    find_lead_ids_by_phone,
    get_lead,
    resolve_enum_id,
    resolve_user_id_by_email,
)
from .bitrix_spa_client import (
    add_item as spa_add_item,
    find_item_by_sympla_event_id as spa_find_item_by_sympla_event_id,
    get_item as spa_get_item,
    update_item as spa_update_item,
)
from .constants import (
    BITRIX_SPA_ENTITY_TYPE_ID,
    BITRIX_WEBHOOK_URL,
    FIELD_DATA_DO_EVENTO,
    FIELD_FILTRAR_EVENTO,
    FIELD_NOME_DO_EVENTO,
    FIELD_ORIGEM,
    FIELD_PARENT_ID_EVENTO_SPA,
    FIELD_PRESENTE_NO_EVENTO,
    FIELD_SPA_NOME_EVENTO,
    FIELD_SPA_SYMPLA_EVENT_ID,
    FIELD_SPA_TOTAL_FALTOSOS,
    FIELD_SPA_TOTAL_INSCRITOS,
    FIELD_SPA_TOTAL_PRESENTES,
    FIELD_SPA_ULTIMA_SINCRONIZACAO,
    FIELD_SYMPLA_EVENT_ID,
    OLD_FUNNEL_STAGES,
    ORIGEM_VALOR_CUPOM_DESCONTO,
    ORIGEM_VALOR_FORMULARIO,
    ORIGEM_VALOR_INSCRITO_DESCONHECIDO,
    ORIGEM_VALOR_TRAFEGO_PAGO,
    STAGE_INSCRITO_PRO_EVENTO,
    STAGES_SAFE_TO_ADVANCE,
    SYMPLA_BASE,
    SYMPLA_TOKEN,
    VALOR_NAO_PRESENTE,
    VALOR_PRESENTE,
)
from .normalization import (
    build_cupom_by_order_id,
    extract_discount_code,
    extract_phone,
    format_event_label,
    format_phone_br,
    normalize_cupom,
    normalize_email,
    normalize_name,
    participant_full_name,
)
from .sympla_client import (
    get_all_events,
    get_sympla_all_orders,
    get_sympla_all_participants,
    list_upcoming_events,
    resolve_event_id,
)

__all__ = [
    "bitrix_call",
    "bitrix_list_all",
    "ensure_enum_value",
    "find_contact_ids_by_email",
    "find_contact_ids_by_phone",
    "find_lead_ids_by_email",
    "find_lead_ids_by_phone",
    "get_lead",
    "resolve_enum_id",
    "resolve_user_id_by_email",
    "spa_add_item",
    "spa_find_item_by_sympla_event_id",
    "spa_get_item",
    "spa_update_item",
    "_merge_enum_items",
    "BITRIX_SPA_ENTITY_TYPE_ID",
    "BITRIX_WEBHOOK_URL",
    "FIELD_DATA_DO_EVENTO",
    "FIELD_FILTRAR_EVENTO",
    "FIELD_NOME_DO_EVENTO",
    "FIELD_ORIGEM",
    "FIELD_PARENT_ID_EVENTO_SPA",
    "FIELD_PRESENTE_NO_EVENTO",
    "FIELD_SPA_NOME_EVENTO",
    "FIELD_SPA_SYMPLA_EVENT_ID",
    "FIELD_SPA_TOTAL_FALTOSOS",
    "FIELD_SPA_TOTAL_INSCRITOS",
    "FIELD_SPA_TOTAL_PRESENTES",
    "FIELD_SPA_ULTIMA_SINCRONIZACAO",
    "FIELD_SYMPLA_EVENT_ID",
    "OLD_FUNNEL_STAGES",
    "ORIGEM_VALOR_CUPOM_DESCONTO",
    "ORIGEM_VALOR_FORMULARIO",
    "ORIGEM_VALOR_INSCRITO_DESCONHECIDO",
    "ORIGEM_VALOR_TRAFEGO_PAGO",
    "STAGE_INSCRITO_PRO_EVENTO",
    "STAGES_SAFE_TO_ADVANCE",
    "SYMPLA_BASE",
    "SYMPLA_TOKEN",
    "VALOR_NAO_PRESENTE",
    "VALOR_PRESENTE",
    "build_cupom_by_order_id",
    "extract_discount_code",
    "extract_phone",
    "format_event_label",
    "format_phone_br",
    "normalize_cupom",
    "normalize_email",
    "normalize_name",
    "participant_full_name",
    "get_all_events",
    "get_sympla_all_orders",
    "get_sympla_all_participants",
    "list_upcoming_events",
    "resolve_event_id",
]
